USE Mobile_manufacture

SELECT * FROM [dbo].[DIM_CUSTOMER]

SELECT * FROM [dbo].[DIM_DATE]

SELECT * FROM [dbo].[DIM_LOCATION]

SELECT * FROM [dbo].[DIM_MANUFACTURER]

SELECT * FROM [dbo].[DIM_MODEL]

SELECT * FROM [dbo].[FACT_TRANSACTIONS]